In [1]:
from obliquetree import Classifier
from obliquetree.utils import export_tree, visualize_tree

In [2]:
import sys
print(f"Python version: {sys.version}")
import obliquetree
print(f"obliquetree location: {obliquetree.__file__}")

Python version: 3.11.13 (main, Jun  5 2025, 13:12:00) [GCC 11.2.0]
obliquetree location: /home/adharsh/anaconda3/envs/dtree/lib/python3.11/site-packages/obliquetree/__init__.py


In [9]:
import pandas as pd

dataset = pd.read_csv('out/dataset.data', header=None)
dataset1 = pd.read_csv('classified_dataset.csv', header=None)

In [10]:
X = dataset.drop(columns=[9])
y = dataset[9]
X1 = dataset1.drop(columns=[2])
y1 = dataset1[2]

In [11]:
# cat_idx = dataset['label'].unique().tolist()
cat_idx = []

In [12]:
clf = Classifier(
    use_oblique=True,
    max_depth=-1,
    random_state=42,
    n_pair=X.shape[1],
    categories=cat_idx
)

In [14]:
clf.fit(X1, y1)

Unique labels: [1.], Expected labels: [0]


ValueError: Classification labels must start from 0 and increment by 1

In [19]:
export_tree(clf, 'dtree123.json')

Exporting tree to JSON format...
State: {'params': {'max_depth': 255, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_impurity_decrease': 0.0, 'random_state': 42, 'n_pair': 9, 'gamma': 1.0, 'max_iter': 100, 'relative_change': 0.001, 'use_oblique': True, 'categories': [], 'ccp_alpha': 0.0, 'task': False, 'n_classes': 2, 'n_features': 9, 'cat_': False}, 'tree': {'n_samples': 2035, 'impurity': 0.0029440564084299847, 'is_leaf': False, 'is_oblique': False, 'feature_idx': 5, 'missing_go_left': True, 'value': 0.9985257985257985, 'threshold': 157.33770699633465, 'left': {'n_samples': 594, 'impurity': 0.010049994898479797, 'is_leaf': False, 'is_oblique': False, 'feature_idx': 5, 'missing_go_left': True, 'value': 0.9949494949494949, 'threshold': 157.33764051693927, 'left': {'n_samples': 593, 'impurity': 0.0067226126051831425, 'is_leaf': False, 'is_oblique': False, 'feature_idx': 5, 'missing_go_left': True, 'value': 0.9966273187183811, 'threshold': 157.32710813962575, 'left': {'n_samples': 52

In [21]:
for d in dataset.iterrows():
    # test decision tree
    dec = clf.predict(d[1].drop(9).values.reshape(1, -1))
    # print(f"Decision: {dec}, Expected: {d[1][9]}")
    if (dec[0] == 1) == False:
        print(d[1].drop(9).values.reshape(1, -1))

[[52.86550235879587 0.0 0.0 -1.0 0.0 36.0 118.0 0.0 1.0]]
[[53.36550235879587 -36.0 0.0 0.0 -1.0 0.0 -39.0 0.0 1.0]]
[[53.365533004482735 -36.0 0.0 0.0 -1.0 -18.0 0.0 0.0 1.0]]
[[53.13840966826024 35.0 -2.0 0.0 1.0 0.0 0.0 -1.0 0.0]]
[[43.4 176.5703 0.0 0.0 -1.0 0.0 0.0 -1.0 0.0]]
[[43.4 0.0 0.0 0.0 1.0 95.90015 0.0 1.0 0.0]]
[[43.4 0.0 12.48202 0.0 -1.0 0.0 0.0 0.0 1.0]]
[[44.0 0.0 0.0 0.0 1.0 142.0 0.0 -1.0 0.0]]
[[43.4 0.0 256.87350000000004 1.0 0.0 0.0 0.0 1.0 0.0]]
[[43.4 0.0 0.0 0.0 -1.0 0.0 0.0 0.5 -0.8660254037840787]]
[[43.4 0.0 0.0 0.0 1.0 260.2549 0.0 -1.0 0.0]]
[[43.4 0.0 0.0 1.0 0.0 315.511 0.0 0.0 -1.0]]
[[43.4 0.0 0.0 1.0 0.0 342.34130000000005 0.0 -1.0 0.0]]
[[43.4 0.0 0.0 0.0 1.0 354.55420000000004 0.0 -1.0 0.0]]
[[44.0 181.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0]]
[[43.4 0.0 0.0 0.0 1.0 0.0 360.6607 -1.0 0.0]]


In [10]:
clf

Classifier(use_oblique=True, max_depth=255, min_samples_leaf=1, min_samples_split=2, min_impurity_decrease=0.0, ccp_alpha=0.0, categories=[], random_state=42, n_pair=9, gamma=1.0, max_iter=100, relative_change=0.001)

In [21]:
# Add at the very top of your script
import sys
print("Already loaded modules:", len(sys.modules))
print("Key scientific modules loaded:", [m for m in sys.modules if any(x in m for x in ['numpy', 'scipy', 'sklearn', 'oblique'])])

Already loaded modules: 1941
Key scientific modules loaded: ['pydevd_plugins.extensions.types.pydevd_plugin_numpy_types', 'obliquetree.src', 'numpy.version', 'numpy._expired_attrs_2_0', 'numpy._utils._convertions', 'numpy._utils', 'numpy._globals', 'numpy._distributor_init', 'numpy.exceptions', 'numpy._core._exceptions', 'numpy._core.printoptions', 'numpy.dtypes', 'numpy._core._multiarray_umath', 'numpy._utils._inspect', 'numpy._core.overrides', 'numpy._core.multiarray', 'numpy._core.umath', 'numpy._core._dtype', 'numpy._core._string_helpers', 'numpy._core._type_aliases', 'numpy._core.numerictypes', 'numpy._core._ufunc_config', 'numpy._core._methods', 'numpy._core.fromnumeric', 'numpy._core._machar', 'numpy._core.shape_base', 'numpy._core._asarray', 'numpy._core.arrayprint', 'numpy._core.numeric', 'numpy._core.einsumfunc', 'numpy._core.function_base', 'numpy._core.getlimits', 'numpy._core.memmap', 'numpy._core.records', 'numpy._core._add_newdocs', 'numpy._core._add_newdocs_scalars', 'n

In [12]:
clf

Classifier(use_oblique=True, max_depth=255, min_samples_leaf=1, min_samples_split=2, min_impurity_decrease=0.0, ccp_alpha=0.0, categories=[], random_state=42, n_pair=9, gamma=1.0, max_iter=100, relative_change=0.001)